// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lctlqufrlgxzvandxdqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdGxxdWZybGd4enZhbmR4ZHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzM5MjAsImV4cCI6MjA2NTc0OTkyMH0.5IY_FXnStswcZyLbd_I4YNXZWYRytBAS5cBJdC85M_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);