// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yknojbanjuchsgctuosg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrbm9qYmFuanVjaHNnY3R1b3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Njk5ODMsImV4cCI6MjA2NTU0NTk4M30.pMVAq9fd1Za91-8M0kaTa2dIDfgMOe69wXPkTkzlOWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);